language: java
install: true
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "Unit tests - OracleJDK 8"
      script: mvn -B -DtestLogLevel=OFF -DexcludedGroups=io.vertx.core.shareddata.HazelcastAsyncApi test
      jdk: oraclejdk8
    - stage: test
      name: "Unit tests - Hazelcast Async API - OracleJDK 8"
      script: mvn -B -DtestLogLevel=OFF -Dgroups=io.vertx.core.shareddata.HazelcastAsyncApi test
      jdk: oraclejdk8
    - name: "Unit tests - OpenJDK 11"
      if: type != pull_request
      script: mvn -B -DtestLogLevel=OFF -DexcludedGroups=io.vertx.core.shareddata.HazelcastAsyncApi test
      jdk: openjdk11
    - name: "Integration tests - OracleJDK 8"
      script: mvn -B -DtestLogLevel=OFF -DskipUnitTests verify
      jdk: oraclejdk8
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
