language: java
install: true
branches:
  only:
  - master
  - /^\d+\.\d+$/
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/vertx/
jobs:
  include:
    - stage: test
      name: "Unit tests - OpenJDK 8"
      script: mvn -B -DtestLogLevel=OFF -DexcludedGroups=io.vertx.core.shareddata.HazelcastAsyncApi test
      jdk: openjdk8
    - stage: test
      name: "Unit tests - Hazelcast Async API - OpenJDK 8"
      script: mvn -B -DtestLogLevel=OFF -Dgroups=io.vertx.core.shareddata.HazelcastAsyncApi test
      jdk: openjdk8
    - name: "Unit tests - OpenJDK 11"
      if: type != pull_request
      script: mvn -B -DtestLogLevel=OFF -DexcludedGroups=io.vertx.core.shareddata.HazelcastAsyncApi test
      jdk: openjdk11
    - name: "Integration tests - OpenJDK 8"
      script: mvn -B -DtestLogLevel=OFF -DskipUnitTests verify
      jdk: openjdk8
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - secure: "Lkfu2lRhyxFtLXeecCn4I4UTthfWxoCOZhybl6NrXeThaeaiHWaVeFK89z0ZSY/jXH3dVRAy5CdSktdLBmEsQ3ElZ3nduI8DJ2D4anp9z3hTlKYn8z4dsgL/6B9xGohT+6m9R+xGfstW/bGQEm/BnQGerH33bwwhDW3JiGe+dqw="
    on_success: always
    on_failure: always
